// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKH85-gi9DHwt8427YP3yjhNyLEyjmAU0',
    appId: '1:195404149002:web:b3945fb970bdd780158af3',
    messagingSenderId: '195404149002',
    projectId: 'flutter-firebase-8110c',
    authDomain: 'flutter-firebase-8110c.firebaseapp.com',
    databaseURL: 'https://flutter-firebase-8110c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-8110c.appspot.com',
    measurementId: 'G-8KWCGCERD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXMRB0uZUmfnI-Q7UzHG-ImLNViqf1YMY',
    appId: '1:195404149002:android:5727e854c2b9bb70158af3',
    messagingSenderId: '195404149002',
    projectId: 'flutter-firebase-8110c',
    databaseURL: 'https://flutter-firebase-8110c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-8110c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBHvT8icQuMKwiO_PQgiq5RimODQqZkRE',
    appId: '1:195404149002:ios:79f6a9413c288a43158af3',
    messagingSenderId: '195404149002',
    projectId: 'flutter-firebase-8110c',
    databaseURL: 'https://flutter-firebase-8110c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-8110c.appspot.com',
    androidClientId: '195404149002-8kf78sv6tej5pfagbsgdndg5qf4tdapg.apps.googleusercontent.com',
    iosClientId: '195404149002-3lenom5kn0o7h0jlijkc32b9h5kcqb3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookinapp01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBHvT8icQuMKwiO_PQgiq5RimODQqZkRE',
    appId: '1:195404149002:ios:d7401d8054b71c6c158af3',
    messagingSenderId: '195404149002',
    projectId: 'flutter-firebase-8110c',
    databaseURL: 'https://flutter-firebase-8110c-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-firebase-8110c.appspot.com',
    androidClientId: '195404149002-8kf78sv6tej5pfagbsgdndg5qf4tdapg.apps.googleusercontent.com',
    iosClientId: '195404149002-dprvajm8kakclojhfs2rqgsugsrkg97m.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookinapp01.RunnerTests',
  );
}
